apiVersion: v1
kind: Service
metadata:
  name: power-xapp-service
  namespace: ntn-oran
  labels:
    app: power-xapp
    component: xapp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
spec:
  type: ClusterIP
  selector:
    app: power-xapp
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  sessionAffinity: None
